#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source ~/.zprofile for non-login interactive shell.
if [[ ( ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Reduce delay when switching to Normal mode.
KEYTIMEOUT=1

# Disable software flow control. This makes Ctrl-S and Ctrl-Q work in terminal.
stty stop undef
stty start undef

# Overwrite existing files when using '>' redirection.
setopt clobber

# Enable GNOME Keyring for terminal applications, such as SSH.
if [ -n "$DESKTOP_SESSION" ]; then
  eval $(gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK
fi

# Enable fuzzy search and completion via fzf.
if [[ -d "$HOME/.config/nvim/plugged/fzf" ]]; then
  source "$HOME/.config/nvim/plugged/fzf/shell/completion.zsh"
  source "$HOME/.config/nvim/plugged/fzf/shell/key-bindings.zsh"
fi

# Use ripgrep to speed up fuzzy search.
if type "rg" > /dev/null; then
  export FZF_DEFAULT_COMMAND="rg --files --hidden --glob \"!.git/*\""
fi
